[project]
name = "livekit-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.34.0",
    "livekit>=0.21.3",
    "livekit-api>=0.8.2",
]
